import { JobRole } from "./types.js";

export const DEFAULT_JOB_ROLES: JobRole[] = [
  {
    id: "role-software-dev",
    title: "Software Developer",
    company: "Technology",
    category: "Technology",
    description: "Build, ship, and improve software applications using modern frameworks, web technologies, and database systems.",
    requiredSkills: ["JavaScript", "TypeScript", "React", "Node.js", "SQL", "Git", "REST API"],
    preferredSkills: ["Docker", "AWS", "GraphQL", "CI/CD", "Testing"],
    experienceLevel: "Mid Level (2-4 years)",
    location: "Remote / Hybrid",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: "role-data-scientist",
    title: "Data Scientist",
    company: "Analytics",
    category: "Technology",
    description: "Turn complex data into actionable decisions using statistical modeling, machine learning, and data pipelines.",
    requiredSkills: ["Python", "Pandas", "NumPy", "SQL", "Machine Learning", "Scikit-Learn", "Data Visualization"],
    preferredSkills: ["PyTorch", "TensorFlow", "Deep Learning", "BigData", "Docker"],
    experienceLevel: "Mid Level (3+ years)",
    location: "Hybrid",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: "role-vlsi-embedded",
    title: "Embedded / VLSI Engineer",
    company: "Hardware Systems",
    category: "Hardware / Engineering",
    description: "Design, develop, and test digital circuits, FPGA logic, and embedded firmware for hardware systems.",
    requiredSkills: ["C", "C++", "Verilog", "FPGA", "Microcontrollers", "RTOS", "Embedded Systems"],
    preferredSkills: ["VHDL", "PCB Design", "ARM Architecture", "SystemVerilog", "Oscilloscopes"],
    experienceLevel: "Mid-Senior Level (3-5 years)",
    location: "On-site",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: "role-hotel-ops-manager",
    title: "Hotel / Operations Manager",
    company: "Hospitality & Management",
    category: "Hospitality",
    description: "Lead memorable, efficient operations, manage staff scheduling, customer service excellence, and guest relations.",
    requiredSkills: ["Hospitality Management", "Customer Service", "Scheduling", "Staff Leadership", "Vendor Management", "Budgeting"],
    preferredSkills: ["Hotel Systems (PMS)", "Conflict Resolution", "Inventory Management", "Event Planning"],
    experienceLevel: "Senior Level (5+ years)",
    location: "On-site",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: "role-marketing-manager",
    title: "Marketing Manager",
    company: "Growth & Brand",
    category: "Marketing",
    description: "Develop digital marketing campaigns, oversee SEO, content strategy, brand communications, and market analytics.",
    requiredSkills: ["Digital Marketing", "SEO", "Content Strategy", "Google Analytics", "Social Media", "Campaign Management"],
    preferredSkills: ["Copywriting", "Email Marketing", "PPC Advertising", "Brand Strategy", "CRM"],
    experienceLevel: "Mid Level (3+ years)",
    location: "Hybrid",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: "role-accountant",
    title: "Accountant",
    company: "Finance",
    category: "Finance",
    description: "Manage financial statements, general ledger, tax compliance, auditing, and ledger reconciliation.",
    requiredSkills: ["Financial Analysis", "Excel", "General Ledger", "Taxation", "Reconciliation", "Accounting Software"],
    preferredSkills: ["QuickBooks", "SAP", "Audit", "Financial Reporting", "CPA"],
    experienceLevel: "Mid Level (2+ years)",
    location: "Hybrid",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
];
